#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Alternative decomposeParDict name:
decompDict="-decomposeParDict system/decomposeParDict.6"
## Standard decomposeParDict name:
# unset decompDict

runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication $decompDict decomposePar

runParallel $decompDict snappyHexMesh -overwrite

#------------------------------------------------------------------------------

