#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
runApplication decomposePar
python system/format_snappyHexMeshDict.py
runApplication surfaceFeatureExtract
runParallel snappyHexMesh -overwrite

restore0Dir -processor
runParallel setFields
runParallel $(getApplication)
runApplication reconstructParMesh -constant
runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
