#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
python system/format_snappyHexMeshDict.py
runApplication surfaceFeatureExtract
runApplication snappyHexMesh

restore0Dir
runApplication setFields
runApplication $(getApplication)

#------------------------------------------------------------------------------
