#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------


./Allrun_pre

restore0Dir

runApplication decomposePar -force
runParallel setFields

runParallel $(getApplication)

runApplication reconstructParMesh -constant
# runApplication reconstructPar -latestTime
runApplication reconstructPar

#------------------------------------------------------------------------------
